# Cloudflare Workers Todo Application Configuration

name = "cloudflare-workers-todo"
main = "src/index.ts"
compatibility_date = "2025-01-01"

# Workers サイト設定は不要（APIのみ）
# account_id と workers_dev はコマンドラインまたは環境変数で指定

# 開発環境（デフォルト）
# KV Namespace ID は、以下のコマンドで作成後、ここに記載してください：
# wrangler kv:namespace create "TODO_KV"
[[kv_namespaces]]
binding = "TODO_KV"
id = "" # TODO: `wrangler kv:namespace create "TODO_KV"` の出力IDをここに設定

# 環境変数（非シークレット）
# セキュリティ上の理由から、API KeyやシークレットはここではなくCloudflare Dashboardまたは`wrangler secret`コマンドで設定してください
[vars]
# ALLOWED_ORIGINS = "*" # 開発環境ではワイルドカードを許可

# 本番環境
[env.production]

# 本番環境のKV Namespace
# 作成コマンド: wrangler kv:namespace create "TODO_KV" --env production
[[env.production.kv_namespaces]]
binding = "TODO_KV"
id = "" # TODO: 本番環境のKV Namespace IDをここに設定

# 本番環境の環境変数
# [env.production.vars]
# 本番環境のCORS設定はシークレットとして管理することを推奨
# セキュリティ上の理由から、特定のオリジンのみを許可してください
# 設定方法: wrangler secret put ALLOWED_ORIGINS --env production

# ビルド設定
[build]
command = "npm run build"

# 開発サーバー設定
[dev]
port = 8787
local_protocol = "http"

# ログレベル
# [observability]
# enabled = true
